FROM node:15 as builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install 

COPY . .

RUN npm run lint && npm run prettier -- --write && CI=true npm run test && npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/build . 

ENTRYPOINT ["nginx", "-g", "daemon off;"]